name: seal_line
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  awesome_snackbar_content: ^0.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0


flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: assets/icons/ic_launcher.png
  min_sdk_android: 21


flutter:
  uses-material-design: true
  generate: true
  assets:
  -  assets/images/